### ISSUE TITLE
The punycode module is deprecated

### ISSUE THREAD

**Issue by reustle** [FurqanSoftware/node-whois#124]
Getting this error every time I start my app, and it seems to trace back to the `whois` package. Would it be a fairly straight forward dependency to remove? Thank you!

```bash
(node:26737) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:96:7)
    at Module._load (node:internal/modules/cjs/loader:1037:17)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/reustle/code/techjanitor/node_modules/whois/index.js:11:14)
    at Object.<anonymous> (/Users/reustle/code/techjanitor/node_modules/whois/index.js:186:4)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
```

**Comment by hjr265** [comment]
Thank you for reporting this! 

New release has a fix for this: https://www.npmjs.com/package/whois v2.14.1

**Comment by reustle** [comment]
Much appreciated, thanks so much
