### ISSUE TITLE
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. 

### ISSUE THREAD

**Issue by Brunovski** [FurqanSoftware/node-whois#82]
The error occurs for domain simo.so

net.js:955
     throw new ERR_SOCKET_BAD_PORT(port);
     ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received  whois.nic.so.
   at lookupAndConnect (net.js:955:13)
   at Socket.connect (net.js:931:5)
   at Object.connect (net.js:156:17)
   at Object.lookup

**Comment by samohan123** [comment]
It might be coz the **localhost** is not defined with the required syntax in the **"hosts"** file of the system.
The file can be located @:

=> **etc/hosts**
(above file for _**linux**_)
or
=> **c:\ Windows \System32\Drivers\ etc \ hosts**
(above file for _**Windows**_)

i.e. file has some wrong input.

So, Try replacing **everything** in that file with the text below as this is the _default_ text that was always there in hosts file when it worked fine:

127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
